version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db_miniapp
    environment:
      POSTGRES_DB: miniapp_db
      POSTGRES_USER: miniapp
      POSTGRES_PASSWORD: miniapp
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: miniAppSpring_backend
    ports:
      - "8081:8080"


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: miniAppSpring_frontend
    ports:
      - "5173:5173"
