
server:
  port: 8090

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true


