#Swagger
# custom path for swagger-ui path: http://localhost:8080/ui
springdoc:
  swagger-ui.path: /ui
# custom path for api docs
  api-docs.path: /api-docs
  swagger-ui.operationsSorter: alpha
  swagger-ui.tagsSorter: alpha

# DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/miniapp_db
    username: miniapp
    password: miniapp
    driverClassName: org.postgresql.Driver

  #limitation for upload file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#  main:
#    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    generate-ddl: true

#Secret keys for token
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
    prefix: Bearer

#Cooke
cooke:
  time:
    live:
      refreshToken: 86000



